name: app

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v7
        with:
          python-version: '3.x'

      - name: prepare dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run tests
        run: pytest tests/test_utils.py
